### PR TITLE
population EDA and ML jupyter notebook from fork

### PR DESCRIPTION
**Pull request by JeffreyAsuncion**
2021.01.27 - JA
- after fork, clone, branch
- added request to pipfile - using 'pipenv install requests'
- added pandas to pipfile - using 'pipenv install pandas'
- no need to add ast to pipfile - already exists
- added sklearn to pipfile - using 'pipenv install sklearn'

### CODE REVIEW

**Review by scrunts23 — DISMISSED** [review]
Looks great.  Thank you for reminding me to install dep.

**Comment by scrunts23** [comment]
Very smart of you to use scaling to work this issue out.

**Review by scrunts23 — DISMISSED** [review]
Looks good.  Great comments and working of the problem.

**Comment by JeffreyAsuncion** [comment]
reviewed just needed to be approved

**Comment by JeffreyAsuncion** [comment]
this was included with the dummy endpoints

**Pull request closed without merging**
